name: Build image, upload, trigger Render deploy

on:
  push:
    branches:
      - main

jobs:
  build-upload-deploy:
    name: Build image, upload, trigger Render deploy
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: maisoup/pink-noise-generator:latest
      -
        name: Trigger Render deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.RENDER_HOOK }}
          method: 'GET'
